#!/bin/env bash


REL="1.0.1 (Kronos)"
BUILD="2"
STUS="CORE"
BT="Dialog APT CORE SCRIPT - $REL"
TITLE="DIALOG-APT $STUS SCRIPT MENU"

MISSING_FILE_CORE_START="mis-CORE-core=NULL"
MISSING_FILE_OTHERS="mis-CORE-res=NULL"

NO_PERMS_INS="perm-ins-x"
NO_PERMS_CORE="perm-CORE-x"


human=$(whoami)
entrance="apt-dialog"
date_time=$(date +%F_%H-%M-%S)
time=$SECONDS

echo "User named : $human, used the $entrance at $date_time . And the Seconds he or she is into the script is $time." >> $HOME/.apt-dialog/log

: ${DIALOG_OK=0}
: ${DIALOG_CANCEL=1}
: ${DIALOG_HELP=2}
: ${DIALOG_EXTRA=3}
: ${DIALOG_ITEM_HELP=4}
: ${DIALOG_ESC=255}

HEIGHT=0
WIDTH=0


exec 3>&1
menu=$(dialog \
    --backtitle "$BT" \
    --title "$TITLE" \
    --clear \
    --yes-label "Go" \
    --no-label "Exit" \
    --menu "Dialog-apt Menu (Version:$REL, Build: $BUILD). Select the Following:" 30 50 9 \
    "1" "Install Packages" \
    "2" "Update Packages and APT" \
    "3" "Remove Packages" \
    "4" "Clean Unecessary Packages" \
    "5" "Find Packages" \
    "6" "Help and Support" \
    "7" "About" \
    "8" "Patch Lists" \
    2>&1 1>&3 \
  )
exit_value=$?
exec 3>&-
case $exit_value in
$DIALOG_CANCEL)
dialog --backtitle "$BT" --title "Exiting" --infobox "Exiting Process $exit_value." $HEIGHT $WIDTH
sleep 3
exit 1
exit 1
exit 1
;;
$DIALOG_HELP)
dialog --backtitle "$BT" --title "$TITLE" --textbox $HOME/.apt-dialog/help.txt
apt-dialog
;;
$DIALOG_ESC)
dialog --backtitle "$BT" --title "Exiting using ESC" --infobox "Exiting using ESC Key.. Exit Code: $exit_value" $HEIGHT $WIDTH
sleep 2
exit 1
;;
esac
case $menu in
1)
 dialog --backtitle "$BT" --title "Loading.." --infobox "Starting Installer Script" $HEIGHT $WIDTH ;
 sleep 2 ;
 command apt-dialog-install
;;
  2)
  dialog --backtitle "$BT" --title "Loading.." --infobox "Starting Update Script" $HEIGHT $WIDTH ;
  sleep 3 ;
  command apt-dialog-update
  ;;
  3)
  dialog --backtitle "$BT" --title "Loading.." --infobox "Starting Remove Packages" $HEIGHT $WIDTH ;
  sleep 2 ;
  command apt-dialog-remove
  ;;
  4)
  dialog --backtitle "$BT" --title "Loading.. " --infobox "Starting Autoremove script" $HEIGHT $WIDTH ;
  sleep 2 ;
  command apt-dialog-autorem
  ;;
  5)
  dialog --backtitle "$BT" --title "Laoding.." --infobox "Starting Find Packages Script" $HEIGHT $WIDTH ;
  sleep 2 ;
  command apt-dialog-search
  ;;
  6)
  dialog --backtitle "$BT" --title "Loading.." --infobox "Starting Help and Support" $HEIGHT $WIDTH ;
  sleep 2 ;
  dialog --backtitle "$BT" --title "Help" --textbox $HOME/.apt-dialog/help.txt ;
  apt-dialog
  ;;
  7)
  dialog --backtitle "$BT" --title "About" --textbox $HOME/apt-dialog/about.txt 30 65 ;
  apt-dialog
  ;;
  8)
  dialog --backtitle "$BT" --title "Patch Lists" --textbox $HOME/.apt-dialog/patch.txt 30 65 ;
  apt-dialog
;;
esac
